name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::703671907665:role/GitHubActionsTerraformRole
          aws-region: us-east-1
          audience: sts.amazonaws.com 

      - name: Verify AWS Credentials
        run: aws sts get-caller-identity

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.4.0'

      - name: Terraform Init (Network)
        run: |
          cd network
          terraform init

      - name: Terraform Plan (Network)
        run: |
          cd network
          terraform plan -var-file="../dev.tfvars"

      - name: Terraform Apply (Network)
        run: |
          cd network
          terraform apply -auto-approve -var-file="../dev.tfvars"

      - name: Terraform Init (Storage)
        run: |
          cd ../storage
          terraform init

      - name: Terraform Plan (Storage)
        run: |
          cd ../storage
          terraform plan -var-file="../dev.tfvars"

      - name: Terraform Apply (Storage)
        run: |
          cd ../storage
          terraform apply -auto-approve -var-file="../dev.tfvars"
