name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Updated to latest version
      
      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2  # Updated to v2
        with:
          role-to-assume: arn:aws:iam::703671907665:role/GitHubActionsTerraformRole
          aws-region: us-east-1
          audience: sts.amazonaws.com  # Ensure correct audience

      - name: Verify AWS Credentials
        run: aws sts get-caller-identity  # Debugging step to verify credentials

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.4.0'

      - name: Terraform Init (Network)
        run: |
          set -e  # Stops execution if any command fails
          terraform -chdir=network init

      - name: Terraform Plan (Network)
        run: |
          set -e
          terraform -chdir=network plan -var-file="../dev.tfvars"

      - name: Terraform Apply (Network)
        run: |
          set -e
          terraform -chdir=network apply -auto-approve -var-file="../dev.tfvars"

      - name: Terraform Init (Storage)
        run: |
          set -e
          terraform -chdir=storage init

      - name: Terraform Plan (Storage)
        run: |
          set -e
          terraform -chdir=storage plan -var-file="../dev.tfvars"

      - name: Terraform Apply (Storage)
        run: |
          set -e
          terraform -chdir=storage apply -auto-approve -var-file="../dev.tfvars"
